export CA_SUB_ENV=main
export CA_DEFAULT_DB_USER=root
export CA_DEFAULT_DB_PASSWORD

export CA_DEFAULT_DB_HOST=127.0.0.1

export CA_RECAPTCHA_SITE_KEY=''
export CA_RECAPTCHA_SECRET=''
export CA_MEMCACHED_INSTANCES=''
