constants:
  sub_env: <%= ENV['CA_SUB_ENV']%>
  recaptcha:
    site_key: <%= ENV['CA_RECAPTCHA_SITE_KEY'] %>
    secret_key: <%= ENV['CA_RECAPTCHA_SECRET'] %>

  secret_encryptor:
      cookie_secret_key: <%= ENV['STA_COOKIE_SECRET_KEY'] %>
      email_tokens_decriptor_key: <%= ENV['STA_EMAIL_TOKENS_DECRIPTOR_KEY'] %>

memcached:
  instances: <%= ENV['CA_MEMCACHED_INSTANCES'] %>