default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true

default_db_identifier: &default_db
  <<: *default
  host: <%= ENV['CA_DEFAULT_DB_HOST']%>
  username: <%= ENV['CA_DEFAULT_DB_USER']%>
  password: <%= ENV['CA_DEFAULT_DB_PASSWORD']%>
  
sub_env_shared_db_identifier: &sub_env_shared_db
  <<: *default
  host: <%= ENV['CA_SUB_ENV_SHARED_DB_HOST']%>
  username: <%= ENV['CA_SUB_ENV_SHARED_DB_USER']%>
  password: <%= ENV['CA_SUB_ENV_SHARED_DB_PASSWORD']%>

saas_and_api_shared_db_identifier: &saas_and_api_shared_db
  <<: *default
  host: <%= ENV['CA_SAAS_SHARED_DB_HOST']%>
  username: <%= ENV['CA_SAAS_SHARED_DB_USER']%>
  password: <%= ENV['CA_SAAS_SHARED_DB_PASSWORD']%>

saas_default_db_identifier: &saas_default_db
  <<: *default
  host: <%= ENV['CA_SAAS_DEFAULT_DB_HOST']%>
  username: <%= ENV['CA_SAAS_DEFAULT_DB_USER']%>
  password: <%= ENV['CA_SAAS_DEFAULT_DB_PASSWORD']%>

# NOTE: Sub env specific databases
<%= Rails.env%>:
  <<: *default_db
  database: company_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>

company_async_hooks_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>:
  <<: *default_db
  database: company_async_hooks_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>

company_client_economy_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>:
  <<: *default_db
  database: company_client_economy_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>

company_big_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>:
  <<: *default_db
  database: company_big_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>

# NOTE: Databases shared between sub environments
company_client_<%= Rails.env%>:
  <<: *sub_env_shared_db
  database: company_client_<%= Rails.env%>

company_user_<%= Rails.env%>:
  <<: *sub_env_shared_db
  database: company_user_<%= Rails.env%>

# NOTE: Database shared between saas and company api
company_saas_shared_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>:
  <<: *saas_and_api_shared_db
  database: company_saas_shared_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>


# NOTE: TEMP LOCATION - Until sass has it's own DB migration management
saas_client_economy_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>:
  <<: *saas_default_db
  database: saas_client_economy_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>

saas_transaction_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>:
  <<: *saas_default_db
  database: saas_transaction_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>

saas_airdrop_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>:
  <<: *saas_default_db
  database: saas_airdrop_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>