default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true
  username: <%= ENV['CA_DEFAULT_DB_USER']%>
  password: <%= ENV['CA_DEFAULT_DB_PASSWORD']%>
  host: <%= ENV['CA_DEFAULT_DB_HOST']%>

<%= Rails.env%>:
  <<: *default
  database: company_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>

company_client_<%= Rails.env%>:
  <<: *default
  database: company_client_<%= Rails.env%>

company_user_<%= Rails.env%>:
  <<: *default
  database: company_user_<%= Rails.env%>

company_email_<%= Rails.env%>:
  <<: *default
  database: company_email_<%= Rails.env%>

company_client_economy_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>:
  <<: *default
  database: company_client_economy_<%= GlobalConstant::Base.sub_env%>_<%= Rails.env%>