default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  collation: utf8_unicode_ci
  reconnect: true
  username: <%= ENV['CA_DEFAULT_DB_USER']%>
  password: <%= ENV['CA_DEFAULT_DB_PASSWORD']%>
  host: <%= ENV['CA_DEFAULT_DB_HOST']%>

<%= Rails.env%>:
  <<: *default
  database: company_users_<%= Rails.env%>

company_clients_<%= Rails.env%>:
  <<: *default
  database: company_clients_<%= Rails.env%>