user:
  details:
    key_template: 'u_d_%{id}'
    expiry_in_seconds: 86400
  secure_details:
    key_template: 'u_sd_%{id}'
    expiry_in_seconds: 86400

client:
  details:
    key_template: 'c_d_%{id}'
    expiry_in_seconds: 86400
  token_details:
    key_template: 'c_td_%{id}'
    expiry_in_seconds: 86400
  token_details_s:
    key_template: 'c_td_s_%{id}'
    expiry_in_seconds: 86400
  api_credentials:
    used_in_shared_env: 1
    key_template: 'c_api_crd_%{id}'
    expiry_in_seconds: 86400
  token_planner_details:
    key_template: 'c_td_p_%{id}'
    expiry_in_seconds: 86400
  tx_status_details:
    key_template: 'c_tx_s_%{id}'
    expiry_in_seconds: 86400
  pending_critical_interaction_ids:
    key_template: 'c_pci_ids_%{id}'
    expiry_in_seconds: 86400
  address:
    key_template: 'c_addr_%{id}'
    expiry_in_seconds: 86400

mics:
  ost_fiat_conversion_factors:
    used_in_shared_env: 1
    key_template: 'c_ost_pp_%{id}'
    expiry_in_seconds: 600